spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    username: root
    password: ashokit@123
    url: jdbc:mysql://localhost:3306/ashokit_ecomm
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
